### ISSUE TITLE
next(automaton) call fails with latest qiskit-terra version

### ISSUE THREAD

**Issue by plecarrour** [hmillerbakewell/partitioned-quantum-cellular-automata#2]
Hi Hector,

I've recently discover the pqca package and try to use it through the pqca Tutorial (https://github.com/iccmr-quantum/PQCA_Tutorial).
The T01-getting_started tutorial works fine till the next(automaton) call.

I found that automaton.py use the deprecated  __add__() method to combine QuantumCircuit

So, I try the following change using the compose() method and it works fine :

Replace : 
    @property
    def combined_circuit(self) -> qiskit.QuantumCircuit:
        """Combine preparation and update circuit."""
        return self.preparation_circuit + self.update_circuit
By :

  @property
    def combined_circuit(self) -> qiskit.QuantumCircuit:
        """Combine preparation and update circuit."""
        return self.preparation_circuit.compose(self.update_circuit)

Hope this may help.

here are the results of the pip show command for the python packages I use :

(OSCQasm) $ pip show qiskit
Name: qiskit
Version: 0.41.1
Summary: Software for developing quantum computing programs
Home-page: https://qiskit.org/
Author: Qiskit Development Team
Author-email: hello@qiskit.org
License: Apache 2.0
Location: /Users/PLC/DEV/OSC-Qasm/OSCQasm/lib/python3.11/site-packages
Requires: qiskit-aer, qiskit-ibmq-provider, qiskit-terra
Required-by: pqca

(OSCQasm) $ pip show qiskit-terra
Name: qiskit-terra
Version: 0.23.2
Summary: Software for developing quantum computing programs
Home-page: https://github.com/Qiskit/qiskit-terra
Author: Qiskit Development Team
Author-email: hello@qiskit.org
License: Apache 2.0
Location: /Users/PLC/DEV/OSC-Qasm/OSCQasm/lib/python3.11/site-packages
Requires: dill, numpy, ply, psutil, python-dateutil, rustworkx, scipy, stevedore, symengine, sympy
Required-by: qiskit, qiskit-aer, qiskit-ibmq-provider

(OSCQasm) $ pip show pqca
Name: pqca
Version: 1.0.2
Summary: Construct and simulate partitioned quantum cellular automata
Home-page: https://github.com/hmillerbakewell/partitioned-quantum-cellular-automata
Author: Hector Miller-Bakewell
Author-email: hmillerbakewell@gmail.com
License: UNKNOWN
Location: /Users/PLC/DEV/OSC-Qasm/OSCQasm/lib/python3.11/site-packages
Requires: qiskit
Required-by: 

Best Regards, 

Pascal

**Comment by hmillerbakewell** [comment]
Thank you for letting me know - the version of pqca on pypi has been
updated to use `compose`, and the qiskit dependency version has been set to
0.42 to avoid these sorts of breaks in future.

The change was made as commit: 136963b
